### ISSUE TITLE
Feature Request: Duplicate struct as -Opts

### ISSUE THREAD

**Issue by poundifdef** [hetznercloud/hcloud-go#341] opened 2023-11-14 22:52 UTC
For this SDK, it would be very useful to be able to take an object returned by a Get() request and turn it into an equivalent that can be used for an Update() request.

For example, I have written a program to upload a new SSL certificate for a load balancer. My code looks something like:

``` go
newLbOpts := hcloud.LoadBalancerUpdateServiceOpts{
  Protocol: oldLbService.Protocol,
  DestinationPort: Ptr(oldLbService.DestinationPort),
  // ...etc...
}
```

This example is particularly cumbersome since I need to do this for the `LoadBalancerUpdateServiceOptsHTTP` and `LoadBalancerUpdateServiceOptsHealthCheckHTTP` objects as well.

It would be awesome if there were a function with the following signature:

``` go
func (s LoadBalancerService) ToUpdateObject() LoadBalancerUpdateServiceOpts {
    // Copies all fields to new object and returns it
}
```

In an ideal world it would perform a deep copy of the underlying sub-documents as well. I don't have a clear idea on how you'd write an automated test to ensure we haven't left any fields behind.

It does look like this already exists in a sense via the private `loadBalancerUpdateServiceOptsToSchema()` function which returns a JSON-serializable `schema.LoadBalancerActionUpdateServiceRequest` struct. I wonder if there's a way to make this more available to consumers of the library.

**Comment by apricote** [comment] 2023-11-15 07:22
This seems to be specific to the `LoadBalancerClient#UpdateService` call, I could not find any other update call in the API that requires so many fields to be set, instead of just replacing what was given.

I think it would be a nice addition to implement that in `hcloud-go`. What do you think @pauhull?

**Comment by pauhull** [comment] 2023-11-15 11:52
Yes, that sounds like a useful improvement to me. I'll be working on an implementation 🙂

**Comment by pauhull** [comment] 2023-11-16 15:49
I've double checked the issue and can't reproduce it on my side. I am able to update a service's certificates using the following code:

```go
lb, _, _ := client.LoadBalancer.GetByName(context.Background(), "load-balancer-1")

client.LoadBalancer.UpdateService(context.Background(), lb, 443, LoadBalancerUpdateServiceOpts{
    HTTP: &LoadBalancerUpdateServiceOptsHTTP{
        Certificates: []*Certificate{
            {
                ID: cid,
            },
        },
    },
})
```

Other fields, like the ones you mentioned, do not seem to be affected by that. Did you try leaving them out, and if so, was there any unexpected behavior? Or did you just go off the documenation because the fields are marked as required in there?

**Comment by poundifdef** [comment] 2023-11-16 16:03
Thank you for the follow-up! You're correct, I only went off the documentation because the fields are marked as required. I had not tried submitting JSON for just that one field.

**Comment by apricote** [comment] 2023-11-23 07:46
We have updated the docs and it will go out with the next deployment. Thank you for reporting this :)

**Closed by apricote** 2023-11-23 07:46 UTC
Labels: Improvement
